version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  front:
    build: ./frontend 
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend