apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    app: prometheus-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 85
    targetPort: 9090
    name: http
